### ISSUE TITLE
Getting "Error occured while authorizing Twitter"

### ISSUE THREAD

**Issue by beaumartinez** [foauth/foauth.org#34]
Hi,

I'm trying to re-authorize my Twitter service, but it doesn't work for me. No matter which scope I set, I get "Error occured while authorizing Twitter" in the flashed message.

**Comment by beaumartinez** [comment]
(It doesn't even redirect me to the Twitter domain to press the "Yes, I authorize foauth" dialog.)

**Comment by beaumartinez** [comment]
For some more context, from looking at Google Chrome's network inspector—

- A POST request is sent to `https://foauth.org/services/twitter/authorize`
- That returns a 302 Found, with Location `https://foauth.org/services`. (This is normally the redirect to the service directly, to authorize there.)

**Comment by johnsheehan** [comment]
Our Twitter app was suspended. We don't yet know if we'll be able to get it reinstated or not.

**Comment by beaumartinez** [comment]
Thanks for telling me @johnsheehan . That's a big shame—foauth makes using Twitter's API in scripts much easier than the alternative. Fingers crossed they reinstate it.

**Comment by gulopine** [comment]
foauth.org violates Twitter's terms of service by being a general-purpose API proxy, which is expressily forbidden. I've removed it from the available services (in 3c1149c) and updated the front page example to use [Pocket](https://getpocket.com/) instead.

It sucks losing what I would consider the "killer" service for foauth.org, but that's the way the cookie crumbles sometimes. Sorry!
